name = "aave-mcp"
main = "src/index.ts"
compatibility_date = "2026-02-10"
compatibility_flags = ["nodejs_compat"]

[[worker_loaders]]
binding = "LOADER"

[placement]
mode = "smart"

[[routes]]
pattern = "aave.sam.engineer/mcp*"
zone_name = "sam.engineer"
